#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Dump go packages
#?? 1.0.0
##?
##? Usage:
##?   go_dump
docs::parse "$@"

GO_DUMP_FILE_PATH="$DOTFILES_PATH/langs/go/packages.txt"

mkdir -p "$DOTFILES_PATH/langs/go"

packages=$(ls -1 "$GOBIN")
paths=()

for p in $packages; do
	path=$(go version -m -v "$GOBIN/$p" | sed -n '2 p' | awk '{print $2}')

	if [[ ${paths[*]} =~ $path ]]; then
		# whatever you want to do when array contains value
		echo "Skipping $p"
		continue
	fi

	version=$(go version -m -v "$GOBIN/$p" | sed -n '3 p' | awk '{print $3}')
	paths+=("$path@$version")
done

printf "%s\n" "${paths[@]}" | sort >"$GO_DUMP_FILE_PATH"
