#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Dump go packages
#?? 1.0.0
##?
##? Usage:
##?   go_dump
docs::parse "$@"

GO_DUMP_FILE_PATH="$DOTFILES_PATH/langs/go/packages.txt"

mkdir -p "$DOTFILES_PATH/langs/go"

ls -1 "$GOBIN" >"$GO_DUMP_FILE_PATH"
