#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Dump npm packages
#?? 1.0.0
##?
##? Usage:
##?   npm_dump
docs::parse "$@"

NPM_DUMP_FILE_PATH="$DOTFILES_PATH/langs/js/global_modules.txt"

mkdir -p "$DOTFILES_PATH/langs/js"

npm ls -g --depth=0 | sed -nE 's/^\W+//p' | tail -n +2 | grep -v npm >"$NPM_DUMP_FILE_PATH"
