#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Clone a github repo
#?? 1.0.0
##?
##? Usage:
##?   clone_repo
docs::parse "$@"

repo_url=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/user/repos?per_page=200" | jq --raw-output ".[].ssh_url" | fzf)
git clone "$repo_url"
echo "$repo_url"
