#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Remove title from headerbar
##?
##? Usage:
##?    headerbar-title-size
docs::parse "$@"

gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Ubuntu Bold 0'
